---
# ============================================================
# VAULT — Secrets chiffrés avec ansible-vault
# ============================================================
# Pour chiffrer ce fichier :
#   ansible-vault encrypt ansible/group_vars/vault.yml
#
# Pour l'éditer après chiffrement :
#   ansible-vault edit ansible/group_vars/vault.yml
#
# Pour exécuter un playbook avec le vault :
#   ansible-playbook playbooks/01_mariadb.yml --ask-vault-pass
# ============================================================

db_root_password: "TP_OPENSOURCE_2026!"
db_repl_password: "TP_OPENSOURCE_2026!"
db_app_password:  "TP_OPENSOURCE_2026!"

haproxy_stats_password: "TP_OPENSOURCE_2026!"
wazuh_api_password:     "TP_OPENSOURCE_2026!"
indexer_password:       "TP_OPENSOURCE_2026!"
